Repository 418sec/huntr, pull requests merged in 2020-11, with the labels that each got.

#842 Mass account creation traduora (updated)
  bounties/other/traduora/2/README.md
  bounties/other/traduora/2/vulnerability.json
Labels: disclosure

#632 Bypassing ratelimiting traduora
  bounties/other/traduora/3/README.md
  bounties/other/traduora/3/vulnerability.json
Labels: disclosure

#833 Authentication Bypass CSRF in uLogger-server
  bounties/other/ulogger-server/1/README.md
  bounties/other/ulogger-server/1/vulnerability.json
Labels: disclosure

#837 Prototype Pollution in @generates/merger
  bounties/npm/@generates/merger/1/README.md
  bounties/npm/@generates/merger/1/vulnerability.json
Labels: disclosure

#857 Prototype Pollution in safe-flat
  bounties/npm/safe-flat/1/README.md
  bounties/npm/safe-flat/1/vulnerability.json
Labels: disclosure

#859 Prototype Pollution in @monabbous/unflatter
  bounties/npm/@monabbous/unflatter/1/README.md
  bounties/npm/@monabbous/unflatter/1/vulnerability.json
Labels: disclosure

#860 Prototype Pollution in @ianwalter/dot
  bounties/npm/@ianwalter/dot/1/README.md
  bounties/npm/@ianwalter/dot/1/vulnerability.json
Labels: disclosure

#825 User name/email enumaration in - Mautic
  bounties/packagist/mautic/core/1/README.md
  bounties/packagist/mautic/core/1/vulnerability.json
Labels: disclosure

#851 Fetch repository primary Codebase on enricher
  tools/process-bounties/enricher.js
Labels: enhancement

#830 Stored XSS in - ForkCMS
  bounties/other/forkcms/1/README.md
  bounties/other/forkcms/1/vulnerability.json
Labels: disclosure

#856 Reflected XSS in - Laracom
  bounties/packagist/jsdecena/laracom/1/README.md
  bounties/packagist/jsdecena/laracom/1/vulnerability.json
Labels: disclosure

#858 Prototype Pollution in objnest
  bounties/npm/objnest/1/README.md
  bounties/npm/objnest/1/vulnerability.json
Labels: disclosure

#861 Prototype Pollution in gson-pointer
  bounties/npm/gson-pointer/1/README.md
  bounties/npm/gson-pointer/1/vulnerability.json
Labels: disclosure

#862 Prototype Pollution in assign.js
  bounties/npm/assign.js/1/README.md
  bounties/npm/assign.js/1/vulnerability.json
Labels: disclosure

#878 Cross-Site Scripting (XSS) in frappe-charts
  bounties/npm/frappe-charts/1/README.md
  bounties/npm/frappe-charts/1/vulnerability.json
Labels: disclosure

#924 Denial of Service (DoS) in argonaut (maven) - 1
  bounties/maven/argonaut/1/vulnerability.json
Labels: discussion

#925 Denial of Service (DoS) in gwtupload (maven) - 1
  bounties/maven/gwtupload/1/vulnerability.json
Labels: discussion

#926 Improper Certificate Validation in http-request (maven) - 1
  bounties/maven/http-request/1/vulnerability.json
Labels: discussion

#927 Directory Traversal in kindeditor (maven) - 1
  bounties/maven/kindeditor/1/vulnerability.json
Labels: discussion

#928 Cross-site Scripting (XSS) in markdown-it-katex (maven) - 1
  bounties/maven/markdown-it-katex/1/vulnerability.json
Labels: discussion

#929 Cross-site Scripting (XSS) in markdown-to-jsx (maven) - 1
  bounties/maven/markdown-to-jsx/1/vulnerability.json
Labels: discussion

#930 Cross-site Scripting (XSS) in openid-connect-java-spring-server (maven) - 1
  bounties/maven/openid-connect-java-spring-server/1/vulnerability.json
Labels: discussion

#931 URL Redirection to Untrusted Site in sonarqube (maven) - 1
  bounties/maven/sonarqube/1/vulnerability.json
Labels: discussion

#932 Regular Expression Denial of Service (ReDoS) in url-regex (maven) - 1
  bounties/maven/url-regex/1/vulnerability.json
Labels: discussion

#933 Regular Expression Denial of Service (ReDoS) in xlsx (maven) - 1
  bounties/maven/xlsx/1/vulnerability.json
Labels: discussion

#934 Arbitrary Code Execution in access-policy (npm) - 1
  bounties/npm/access-policy/1/vulnerability.json
Labels: discussion

#935 Remote Code Execution in alfred-workflow-nodejs (npm) - 1
  bounties/npm/alfred-workflow-nodejs/1/vulnerability.json
Labels: discussion

#936 Cross-site Scripting (XSS) in angular-redactor (npm) - 1
  bounties/npm/angular-redactor/1/vulnerability.json
Labels: discussion

#937 Cross-site Scripting (XSS) in ant-design-pro (npm) - 1
  bounties/npm/ant-design-pro/1/vulnerability.json
Labels: discussion

#938 Remote Code Execution in antlr4-cli (npm) - 1
  bounties/npm/antlr4-cli/1/vulnerability.json
Labels: discussion

#939 Directory Traversal in aso-server (npm) - 1
  bounties/npm/aso-server/1/vulnerability.json
Labels: discussion

#940 Prototype Pollution in assign.js (npm) - 1
  bounties/npm/assign.js/1/vulnerability.json
Labels: discussion

#941 Cross-site Scripting (XSS) in bizcharts (npm) - 1
  bounties/npm/bizcharts/1/vulnerability.json
Labels: discussion

#942 Insufficient Input Validation in bson-objectid (npm) - 1
  bounties/npm/bson-objectid/1/vulnerability.json
Labels: discussion

#943 OS Command Injection in bundle-phobia-cli (npm) - 1
  bounties/npm/bundle-phobia-cli/1/vulnerability.json
Labels: discussion

#944 Prototype Pollution in casperjs (npm) - 1
  bounties/npm/casperjs/1/vulnerability.json
Labels: discussion

#945 Arbitrary Code Execution in cd-messenger (npm) - 1
  bounties/npm/cd-messenger/1/vulnerability.json
Labels: discussion

#946 Improper Access Control in cezerin (npm) - 1
  bounties/npm/cezerin/1/vulnerability.json
Labels: discussion

#947 Command Injection in clamscan (npm) - 1
  bounties/npm/clamscan/1/vulnerability.json
Labels: discussion

#948 Command Injection in compass-compile (npm) - 1
  bounties/npm/compass-compile/1/vulnerability.json
Labels: discussion

#950 Remote Code Execution in count-git-tags (npm) - 1
  bounties/npm/count-git-tags/1/vulnerability.json
Labels: discussion

#951 Remote Code Execution in create-git (npm) - 1
  bounties/npm/create-git/1/vulnerability.json
Labels: discussion

#952 Command Injection in curlrequest (npm) - 1
  bounties/npm/curlrequest/1/vulnerability.json
Labels: discussion

#953 Arbitrary File Read in curlrequest (npm) - 2
  bounties/npm/curlrequest/2/vulnerability.json
Labels: discussion

#954 Prototype Pollution in datatables.net (npm) - 1
  bounties/npm/datatables.net/1/vulnerability.json
Labels: discussion

#955 Prototype Pollution in deep-get-set (npm) - 1
  bounties/npm/deep-get-set/1/vulnerability.json
Labels: discussion

#956 Prototype Pollution in deep-merge-object (npm) - 1
  bounties/npm/deep-merge-object/1/vulnerability.json
Labels: discussion

#957 Regular Expression Denial of Service (ReDoS) in dns-sync (npm) - 1
  bounties/npm/dns-sync/1/vulnerability.json
Labels: discussion

#958 Prototype Pollution in doc-path (npm) - 1
  bounties/npm/doc-path/1/vulnerability.json
Labels: discussion

#959 Command Injection in docker-compose-remote-api (npm) - 1
  bounties/npm/docker-compose-remote-api/1/vulnerability.json
Labels: discussion

#960 Prototype Pollution in dot-notes-js (npm) - 1
  bounties/npm/dot-notes-js/1/vulnerability.json
Labels: discussion

#962 Cross-site Scripting (XSS) in editor.md (npm) - 1
  bounties/npm/editor.md/1/vulnerability.json
Labels: discussion

#963 Command Injection in effect (npm) - 1
  bounties/npm/effect/1/vulnerability.json
Labels: discussion

#964 Signature Validation Bypass in electron-builder (npm) - 1
  bounties/npm/electron-builder/1/vulnerability.json
Labels: discussion

#965 Remote Code Execution in enpeem (npm) - 1
  bounties/npm/enpeem/1/vulnerability.json
Labels: discussion

#966 Rate Limiting Bypass in express-brute (npm) - 1
  bounties/npm/express-brute/1/vulnerability.json
Labels: discussion

#967 Cross-site Request Forgery (CSRF) in express-cart (npm) - 1
  bounties/npm/express-cart/1/vulnerability.json
Labels: discussion

#968 Prototype Pollution in extendify (npm) - 1
  bounties/npm/extendify/1/vulnerability.json
Labels: discussion

#969 Prototype Pollution in fast-json-patch (npm) - 1
  bounties/npm/fast-json-patch/1/vulnerability.json
Labels: discussion

#970 Remote Code Execution in ffmpeg-normalize (npm) - 1
  bounties/npm/ffmpeg-normalize/1/vulnerability.json
Labels: discussion

#971 Prototype Pollution in fine-uploader (npm) - 1
  bounties/npm/fine-uploader/1/vulnerability.json
Labels: discussion

#972 Prototype Pollution in flat (npm) - 1
  bounties/npm/flat/1/vulnerability.json
Labels: discussion

#973 Cross-site Scripting (XSS) in frappe-charts (npm) - 1
  bounties/npm/frappe-charts/1/vulnerability.json
Labels: discussion

#974 Command Injection in fsa (npm) - 1
  bounties/npm/fsa/1/vulnerability.json
Labels: discussion

#975 Prototype Pollution in fun-map (npm) - 1
  bounties/npm/fun-map/1/vulnerability.json
Labels: discussion

#976 Prototype Pollution in gammautils (npm) - 1
  bounties/npm/gammautils/1/vulnerability.json
Labels: discussion

#977 Remote Code Execution in gify (npm) - 1
  bounties/npm/gify/1/vulnerability.json
Labels: discussion

#979 Remote Code Execution in git-lab-cli (npm) - 1
  bounties/npm/git-lab-cli/1/vulnerability.json
Labels: discussion

#980 Remote Code Execution in git-revision-webpack-plugin (npm) - 1
  bounties/npm/git-revision-webpack-plugin/1/vulnerability.json
Labels: discussion

#981 Remote Code Execution in git-static (npm) - 1
  bounties/npm/git-static/1/vulnerability.json
Labels: discussion

#982 Remote Code Execution in git-stats (npm) - 1
  bounties/npm/git-stats/1/vulnerability.json
Labels: discussion

#983 Command Injection in git-tags-remote (npm) - 1
  bounties/npm/git-tags-remote/1/vulnerability.json
Labels: discussion

#984 Remote Code Execution in gitlogplus (npm) - 1
  bounties/npm/gitlogplus/1/vulnerability.json
Labels: discussion

#985 Remote Code Execution in gitwin (npm) - 1
  bounties/npm/gitwin/1/vulnerability.json
Labels: discussion

#986 Remote Code Execution in gity (npm) - 1
  bounties/npm/gity/1/vulnerability.json
Labels: discussion

#987 Prototype Pollution in grunt-util-property (npm) - 1
  bounties/npm/grunt-util-property/1/vulnerability.json
Labels: discussion

#988 Prototype Pollution in gson-pointer (npm) - 1
  bounties/npm/gson-pointer/1/vulnerability.json
Labels: discussion

#989 Prototype Pollution in gson-query (npm) - 1
  bounties/npm/gson-query/1/vulnerability.json
Labels: discussion

#990 Command Injection in gulp-scss-lint (npm) - 1
  bounties/npm/gulp-scss-lint/1/vulnerability.json
Labels: discussion

#991 Command Injection in gulp-styledocco (npm) - 1
  bounties/npm/gulp-styledocco/1/vulnerability.json
Labels: discussion

#992 Command Injection in gulp-tape (npm) - 1
  bounties/npm/gulp-tape/1/vulnerability.json
Labels: discussion

#993 Path Traversal via Symbolic Link in hapi (npm) - 1
  bounties/npm/hapi/1/vulnerability.json
Labels: discussion

#995 Cross-site Scripting (XSS) in hexo-admin (npm) - 1
  bounties/npm/hexo-admin/1/vulnerability.json
Labels: discussion

#996 Stored Cross-site Scripting (XSS) in hichat (npm) - 1
  bounties/npm/hichat/1/vulnerability.json
Labels: discussion

#997 Arbitrary File Read in html-pdf (npm) - 1
  bounties/npm/html-pdf/1/vulnerability.json
Labels: discussion

#998 Denial of Service (DoS) in html-to-text (npm) - 1
  bounties/npm/html-to-text/1/vulnerability.json
Labels: discussion

#999 Path Traversal in http-server (npm) - 1
  bounties/npm/http-server/1/vulnerability.json
Labels: discussion

#1000 Path Traversal in httpster (npm) - 1
  bounties/npm/httpster/1/vulnerability.json
Labels: discussion

#1001 Command Injection in idevicekit (npm) - 1
  bounties/npm/idevicekit/1/vulnerability.json
Labels: discussion

#1002 Arbitrary Code Execution in infraserver (npm) - 1
  bounties/npm/infraserver/1/vulnerability.json
Labels: discussion

#1003 Prototype Pollution in ini-parser (npm) - 1
  bounties/npm/ini-parser/1/vulnerability.json
Labels: discussion

#1004 Command Injection in install-package (npm) - 1
  bounties/npm/install-package/1/vulnerability.json
Labels: discussion

#1005 Command Injection in jison (npm) - 1
  bounties/npm/jison/1/vulnerability.json
Labels: discussion

#1006 Cross-site Scripting (XSS) in jquery-confirm (npm) - 1
  bounties/npm/jquery-confirm/1/vulnerability.json
Labels: discussion

#1007 Cross-site Scripting (XSS) in jquery-form (npm) - 1
  bounties/npm/jquery-form/1/vulnerability.json
Labels: discussion

#1008 Command Injection in jscover (npm) - 1
  bounties/npm/jscover/1/vulnerability.json
Labels: discussion

#1009 Remote Code Execution in jshint (npm) - 1
  bounties/npm/jshint/1/vulnerability.json
Labels: discussion

#1010 Prototype Pollution in json-merge-patch (npm) - 1
  bounties/npm/json-merge-patch/1/vulnerability.json
Labels: discussion

#1011 Prototype Pollution in json-ptr (npm) - 1
  bounties/npm/json-ptr/1/vulnerability.json
Labels: discussion

#1012 Prototype Pollution in json8-patch (npm) - 1
  bounties/npm/json8-patch/1/vulnerability.json
Labels: discussion

#1013 Prototype Pollution in json8-pointer (npm) - 1
  bounties/npm/json8-pointer/1/vulnerability.json
Labels: discussion

#1014 Prototype Pollution in just-diff-apply (npm) - 1
  bounties/npm/just-diff-apply/1/vulnerability.json
Labels: discussion

#1015 Prototype Pollution in just-safe-set (npm) - 1
  bounties/npm/just-safe-set/1/vulnerability.json
Labels: discussion

#1016 Command Injection in karma-mojo (npm) - 1
  bounties/npm/karma-mojo/1/vulnerability.json
Labels: discussion

#1018 Cross-Site Request Forgery (CSRF) in lets-chat (npm) - 1
  bounties/npm/lets-chat/1/vulnerability.json
Labels: discussion

#1019 Remote Code Execution in libreoffice-convert (npm) - 1
  bounties/npm/libreoffice-convert/1/vulnerability.json
Labels: discussion

#1020 Prototype Pollution in licia (npm) - 1
  bounties/npm/licia/1/vulnerability.json
Labels: discussion

#1021 Command Injection in limdu (npm) - 1
  bounties/npm/limdu/1/vulnerability.json
Labels: discussion

#1022 Regular Expression Denial of Service (ReDoS) in locutus (npm) - 1
  bounties/npm/locutus/1/vulnerability.json
Labels: discussion

#1023 Command Injection in lsof (npm) - 1
  bounties/npm/lsof/1/vulnerability.json
Labels: discussion

#1024 Command Injection in macaca-adb (npm) - 1
  bounties/npm/macaca-adb/1/vulnerability.json
Labels: discussion

#1025 Remote Code Execution in makedeb (npm) - 1
  bounties/npm/makedeb/1/vulnerability.json
Labels: discussion

#1026 Path Traversal in marscode (npm) - 1
  bounties/npm/marscode/1/vulnerability.json
Labels: discussion

#1027 Prototype Pollution in merge (npm) - 1
  bounties/npm/merge/1/vulnerability.json
Labels: discussion

#1028 Remote Code Execution in meta-git (npm) - 1
  bounties/npm/meta-git/1/vulnerability.json
Labels: discussion

#1029 Denial of Service in metascraper-helpers (npm) - 1
  bounties/npm/metascraper-helpers/1/vulnerability.json
Labels: discussion

#1030 Path Traversal in min-http-server (npm) - 1
  bounties/npm/min-http-server/1/vulnerability.json
Labels: discussion

#1031 Arbitrary Code Injection in mongo-parse (npm) - 1
  bounties/npm/mongo-parse/1/vulnerability.json
Labels: discussion

#1032 Arbitrary Code Injection in mongui (npm) - 1
  bounties/npm/mongui/1/vulnerability.json
Labels: discussion

#1033 Arbitrary Code Execution in mosc (npm) - 1
  bounties/npm/mosc/1/vulnerability.json
Labels: discussion

#1034 Remote Code Execution in mrgit (npm) - 1
  bounties/npm/mrgit/1/vulnerability.json
Labels: discussion

#1035 Prototype Pollution in nessy (npm) - 1
  bounties/npm/nessy/1/vulnerability.json
Labels: discussion

#1036 Directory Traversal in node-asset-cache (npm) - 1
  bounties/npm/node-asset-cache/1/vulnerability.json
Labels: discussion

#1037 Download of Resources Without Integrity Check in node-browser (npm) - 1
  bounties/npm/node-browser/1/vulnerability.json
Labels: discussion

#1038 Command Injection in node-idevice (npm) - 1
  bounties/npm/node-idevice/1/vulnerability.json
Labels: discussion

#1039 Command Injection in node-imagickal (npm) - 1
  bounties/npm/node-imagickal/1/vulnerability.json
Labels: discussion

#1040 Arbitrary Code Execution in node-import (npm) - 1
  bounties/npm/node-import/1/vulnerability.json
Labels: discussion

#1041 Command Injection in node-key-sender (npm) - 1
  bounties/npm/node-key-sender/1/vulnerability.json
Labels: discussion

#1042 Command Injection in node-pngdefry (npm) - 1
  bounties/npm/node-pngdefry/1/vulnerability.json
Labels: discussion

#1043 Buffer Overflow in node-pngdefry (npm) - 2
  bounties/npm/node-pngdefry/2/vulnerability.json
Labels: discussion

#1044 Command Injection in node-prompt-here (npm) - 1
  bounties/npm/node-prompt-here/1/vulnerability.json
Labels: discussion

#1045 Command Injection in node-rpm-builder (npm) - 1
  bounties/npm/node-rpm-builder/1/vulnerability.json
Labels: discussion

#1046 Code Injection in node-rsync (npm) - 1
  bounties/npm/node-rsync/1/vulnerability.json
Labels: discussion

#1047 Code Injection in node-scp (npm) - 1
  bounties/npm/node-scp/1/vulnerability.json
Labels: discussion

#1048 Remote Code Execution in node-svn-ultimate (npm) - 1
  bounties/npm/node-svn-ultimate/1/vulnerability.json
Labels: discussion

#1049 Remote Code Execution in node-tool-utils (npm) - 1
  bounties/npm/node-tool-utils/1/vulnerability.json
Labels: discussion

#1050 Remote Code Execution in node-wkhtmltopdf (npm) - 1
  bounties/npm/node-wkhtmltopdf/1/vulnerability.json
Labels: discussion

#1051 Remote Code Execution in npm-git-publish (npm) - 1
  bounties/npm/npm-git-publish/1/vulnerability.json
Labels: discussion

#1052 Command Injection in npm-programmatic (npm) - 1
  bounties/npm/npm-programmatic/1/vulnerability.json
Labels: discussion

#1053 Resources Downloaded over Insecure Protocol in nw-with-arm (npm) - 1
  bounties/npm/nw-with-arm/1/vulnerability.json
Labels: discussion

#1054 Prototype Pollution in object-path (npm) - 1
  bounties/npm/object-path/1/vulnerability.json
Labels: discussion

#1055 Prototype Pollution in objnest (npm) - 1
  bounties/npm/objnest/1/vulnerability.json
Labels: discussion

#1056 Prototype Pollution in objutil (npm) - 1
  bounties/npm/objutil/1/vulnerability.json
Labels: discussion

#1057 Remote Code Execution in office-converter (npm) - 1
  bounties/npm/office-converter/1/vulnerability.json
Labels: discussion

#1058 Command Injection in op-browser (npm) - 1
  bounties/npm/op-browser/1/vulnerability.json
Labels: discussion

#1059 Resources Downloaded over Insecure Protocol in openframe-image (npm) - 1
  bounties/npm/openframe-image/1/vulnerability.json
Labels: discussion

#1060 Remote Code Execution in pdf-merge (npm) - 1
  bounties/npm/pdf-merge/1/vulnerability.json
Labels: discussion

#1061 Remote Code Execution in pdf-toolz (npm) - 1
  bounties/npm/pdf-toolz/1/vulnerability.json
Labels: discussion

#1062 Prototype Pollution in phpjs (npm) - 1
  bounties/npm/phpjs/1/vulnerability.json
Labels: discussion

#1063 Directory Traversal in quickserver (npm) - 1
  bounties/npm/quickserver/1/vulnerability.json
Labels: discussion
