Repository 418sec/huntr, pull requests merged in 2020-12, with the labels that each got.

#1312 Added `n/a` to `Fixer` for completed/invalid disclosures
  bounties/maven/kindeditor/1/vulnerability.json
  bounties/maven/markdown-to-jsx/1/vulnerability.json
  bounties/maven/sonarqube/1/vulnerability.json
  bounties/npm/angular-redactor/1/vulnerability.json
  bounties/npm/ant-design-pro/1/vulnerability.json
  bounties/npm/compass-compile/1/vulnerability.json
  bounties/npm/dot-json/1/vulnerability.json
  bounties/npm/hapi/1/vulnerability.json
  bounties/npm/hexo-admin/1/vulnerability.json
  bounties/npm/html-to-text/1/vulnerability.json
  bounties/npm/limdu/1/vulnerability.json
  bounties/npm/meta-git/1/vulnerability.json
  bounties/npm/metascraper-helpers/1/vulnerability.json
  bounties/npm/node-imagickal/1/vulnerability.json
  bounties/npm/node-svn-ultimate/1/vulnerability.json
  bounties/npm/npm-git-publish/1/vulnerability.json
  bounties/npm/squel/1/vulnerability.json
  bounties/npm/useragent/1/vulnerability.json
  bounties/npm/windows-shortcuts/1/vulnerability.json
  bounties/other/odoo/1/vulnerability.json
  bounties/packagist/centreon/centreon/1/vulnerability.json
Labels: enhancement

#1313 Removing False bounties
  bounties/npm/express-cart/1/vulnerability.json
  bounties/npm/http-server/1/vulnerability.json
  bounties/npm/node-pngdefry/2/vulnerability.json
  bounties/packagist/nilsteampassnet/teampass/1/vulnerability.json
  bounties/pip/pyyaml/1/vulnerability.json
  bounties/pip/uvicorn/1/vulnerability.json
  bounties/rubygems/colorscore/1/vulnerability.json
  bounties/rubygems/cucumber-ruby/1/vulnerability.json
Labels: enhancement

#1395 Prototype Pollution in mout
  bounties/npm/mout/1/README.md
  bounties/npm/mout/1/vulnerability.json
Labels: disclosure

#1378 Prototype Pollution in fast-toml
  bounties/npm/fast-toml/1/README.md
  bounties/npm/fast-toml/1/vulnerability.json
Labels: disclosure

#1370 Prototype Pollution in multi-ini
  bounties/npm/multi-ini/1/README.md
  bounties/npm/multi-ini/1/vulnerability.json
Labels: disclosure

#1369 Prototype Pollution in properties-reader
  bounties/npm/properties-reader/1/README.md
  bounties/npm/properties-reader/1/vulnerability.json
Labels: disclosure

#1368 Prototype Pollution in js-ini
  bounties/npm/js-ini/1/README.md
  bounties/npm/js-ini/1/vulnerability.json
Labels: disclosure

#1367 Command Injection in last-commit-log
  bounties/npm/last-commit-log/1/README.md
  bounties/npm/last-commit-log/1/vulnerability.json
Labels: disclosure

#1361 feat(landing-page)
  src/layouts/default.vue
  src/pages/index.vue
Labels: open-source

#1359 WIP: feat(blog): adding all text based blogs to the content folder
  content/blog/abhiram-v-my-journey-with-huntr.md
  content/blog/april-highlights.md
  content/blog/hello-world.md
  content/blog/july-highlights.md
  content/blog/june-highlights.md
  content/blog/lodash-a-recent-vulnerability.md
  content/blog/may-highlights.md
  content/blog/september-highlights.md
  content/blog/the-greatest-asset-in-open-source.md
Labels: open-source

#1405 feat(open-source-blog-page)
  src/layouts/default.vue
  src/nuxt.config.js
  src/pages/blog/_slug.vue
  src/pages/blog/index.vue
  src/tailwind.config.js
Labels: open-source

#1407 Prototype Pollution in obj-unflatten
  bounties/npm/obj-unflatten/1/README.md
  bounties/npm/obj-unflatten/1/vulnerability.json
Labels: disclosure

#1389 Cross-Site Request Forgery in strider
  bounties/other/strider/1/README.md
  bounties/other/strider/1/vulnerability.json
Labels: disclosure

#1398 Prototype Pollution in deep-override
  bounties/npm/deep-override/1/README.md
  bounties/npm/deep-override/1/vulnerability.json
Labels: disclosure

#1380 Cross-Site Scripting (XSS) in openfire-nodejs-plugin
  bounties/other/openfire-nodejs-plugin/1/README.md
  bounties/other/openfire-nodejs-plugin/1/vulnerability.json
Labels: disclosure

#1397 Prototype Pollution in set-or-get
  bounties/npm/set-or-get/1/README.md
  bounties/npm/set-or-get/1/vulnerability.json
Labels: disclosure

#1390 Cross-Site Scripting (XSS) in openfire-bookmarks-plugin
  bounties/other/openfire-bookmarks-plugin/1/README.md
  bounties/other/openfire-bookmarks-plugin/1/vulnerability.json
Labels: disclosure

#1379 Cross-Site Scripting (XSS) in openfire-dbaccess-plugin
  bounties/other/openfire-dbaccess-plugin/1/README.md
  bounties/other/openfire-dbaccess-plugin/1/vulnerability.json
Labels: disclosure

#1318 Account takeover with CSRF vulnerability in teedy
  bounties/other/teedy/1/README.md
  bounties/other/teedy/1/vulnerability.json
Labels: disclosure

#1321 Cross-Site Scripting in apexcharts
  bounties/npm/apexcharts/1/README.md
  bounties/npm/apexcharts/1/vulnerability.json
Labels: disclosure

#1428 Prototype Pollution in path-toolkit
  bounties/npm/path-toolkit/1/README.md
  bounties/npm/path-toolkit/1/vulnerability.json
Labels: disclosure

#1427 Prototype Pollution in expand-keys
  bounties/npm/expand-keys/1/README.md
  bounties/npm/expand-keys/1/vulnerability.json
Labels: disclosure

#1426 Prototype Pollution in nest-deep
  bounties/npm/nest-deep/1/README.md
  bounties/npm/nest-deep/1/vulnerability.json
Labels: disclosure

#1425 Prototype Pollution in nested-objects-util
  bounties/npm/nested-objects-util/1/README.md
  bounties/npm/nested-objects-util/1/vulnerability.json
Labels: disclosure

#1424 Prototype Pollution in easydot
  bounties/npm/easydot/1/README.md
  bounties/npm/easydot/1/vulnerability.json
Labels: disclosure

#1423 Prototype Pollution in deepr
  bounties/npm/deepr/1/README.md
  bounties/npm/deepr/1/vulnerability.json
Labels: disclosure

#1422 Prototype Pollution in deep-merger
  bounties/npm/deep-merger/1/README.md
  bounties/npm/deep-merger/1/vulnerability.json
Labels: disclosure

#1421 Prototype Pollution in ts-nodash
  bounties/npm/ts-nodash/1/README.md
  bounties/npm/ts-nodash/1/vulnerability.json
Labels: disclosure

#1420 Prototype Pollution in @common-utilities/merge-objects
  bounties/npm/@common-utilities/merge-objects/1/README.md
  bounties/npm/@common-utilities/merge-objects/1/vulnerability.json
Labels: disclosure

#1429 Prototype Pollution in sgt-fields
  bounties/npm/sgt-fields/1/README.md
  bounties/npm/sgt-fields/1/vulnerability.json
Labels: disclosure

#1331 Arbitrary Code Execution in microsoft/computervision-recipes
  bounties/pip/computervision-recipes/1/README.md
  bounties/pip/computervision-recipes/1/vulnerability.json
Labels: disclosure

#1365 Arbitrary Code Execution in training code of Yolov5 Object Detection Model
  bounties/other/yolov5/1/README.md
  bounties/other/yolov5/1/vulnerability.json
Labels: disclosure

#1366 Cross-Site Scripting (XSS) in drag-on-drop
  bounties/npm/drag-on-drop/1/README.md
  bounties/npm/drag-on-drop/1/vulnerability.json
Labels: disclosure

#1391 Cross-Site Scripting (XSS) in openfire-fastpath-plugin
  bounties/other/openfire-fastpath-plugin/1/README.md
  bounties/other/openfire-fastpath-plugin/1/vulnerability.json
Labels: disclosure

#1329 Arbitrary Code Execution in Microsoft/qlib
  bounties/pip/qlib/1/README.md
  bounties/pip/qlib/1/vulnerability.json
Labels: disclosure

#1409 SSRF in - Cairosvg
  bounties/pip/CairoSVG/1/README.md
  bounties/pip/CairoSVG/1/vulnerability.json
Labels: disclosure

#1406 Cross-Site Scripting (XSS) in openfire-clientControl-plugin
  bounties/other/openfire-clientControl-plugin/1/README.md
  bounties/other/openfire-clientControl-plugin/1/vulnerability.json
Labels: disclosure

#1310 Arbitrary Code execution in Mozilla/DeepSpeech
  bounties/other/DeepSpeech/1/README.md
  bounties/other/DeepSpeech/1/vulnerability.json
Labels: disclosure

#1320 Stored XSS in Maxsite-CMS
  bounties/other/maxsite/README.md
  bounties/other/maxsite/vulnerability.json
Labels: disclosure

#1333 Cross-Site Scripting in @antv/g2
  bounties/npm/@antv/g2/1/README.md
  bounties/npm/@antv/g2/1/vulnerability.json
Labels: disclosure

#1363 Cross-Site Scripting (XSS) in netlify-cms-widget-markdown
  bounties/npm/netlify-cms-widget-markdown/1/README.md
  bounties/npm/netlify-cms-widget-markdown/1/vulnerability.json
Labels: disclosure

#1392 Cross-Site Scripting (XSS) in openfire-userCreation-plugin
  bounties/other/openfire-userCreation-plugin/1/README.md
  bounties/other/openfire-userCreation-plugin/1/vulnerability.json
Labels: disclosure

#1314 Arbitrary Code Execution in Tensorflow/models
  bounties/other/models/1/README.md
  bounties/other/models/1/vulnerability.json
Labels: disclosure

#1315 Arbitrary Code Execution in Tensorflow/tpu
  bounties/other/tpu/1/README.md
  bounties/other/tpu/1/vulnerability.json
Labels: disclosure

#1317 Arbitrary Code Execution in code of NVIDIA/DeepLearningExamples
  bounties/other/DeepLearningExamples/1/README.md
  bounties/other/DeepLearningExamples/1/vulnerability.json
Labels: disclosure

#1328 Arbitrary Code Execution in Microsoft/nni
  bounties/pip/nni/1/README.md
  bounties/pip/nni/1/vulnerability.json
Labels: disclosure

#1332 Lack of Rate Limiting in ApostropheCMS
  bounties/npm/apostrophe/1/README.md
  bounties/npm/apostrophe/1/vulnerability.json
Labels: disclosure

#1334 Arbitrary Code Execution in Duktape tools
  bounties/other/duktape/1/README.md
  bounties/other/duktape/1/vulnerability.json
Labels: disclosure

#1337 Arbitrary Code Execution in pytorch/.../selector.py
  bounties/pip/pytorch/1/README.md
  bounties/pip/pytorch/1/vulnerability.json
Labels: disclosure

#1341 Arbitrary code execution via Insecure YAML deserialization in NVIDIA/runx
  bounties/pip/runx/1/README.md
  bounties/pip/runx/1/vulnerability.json
Labels: disclosure

#1348 Arbitrary code execution via Insecure YAML deserialization in google/capirca
  bounties/pip/caprica/1/README.md
  bounties/pip/caprica/1/vulnerability.json
Labels: disclosure

#1349 Arbitrary Code Execution in deep_sort_pytorch
  bounties/other/deep_sort_pytorch/1/README.md
  bounties/other/deep_sort_pytorch/1/vulnerability.json
Labels: disclosure

#1350 Code execution via insecure deserialization in networkx
  bounties/pip/networkx/1/README.md
  bounties/pip/networkx/1/vulnerability.json
Labels: disclosure

#1362 Arbitrary Code Execution in cluster-serving-cli in analytics-zoo
  bounties/other/analytics-zoo/1/README.md
  bounties/other/analytics-zoo/1/vulnerability.json
Labels: disclosure

#1364 Arbitrary code Execution in Yolov3 training code
  bounties/other/yolov3/1/README.md
  bounties/other/yolov3/1/vulnerability.json
Labels: disclosure

#1374 Arbitrary Code Execution in apollo gen_proto_file.py
  bounties/other/apollo/1/README.md
  bounties/other/apollo/1/vulnerability.json
Labels: disclosure

#1382 Insecure desearilization in Spotify/Chartify
  bounties/pip/chartify/1/README.md
  bounties/pip/chartify/1/vulnerability.json
Labels: disclosure

#1384 Arbitrary Code Execution in kubernetes/hack/verify-publishing-bot.py
  bounties/other/kubernetes/1/README.md
  bounties/other/kubernetes/1/vulnerability.json
Labels: disclosure
