Repository 418sec/huntr, pull requests merged in 2021-01, with the labels that each got.

#1326 CSRF in Subrion-CMS
  bounties/other/subrion/README.md
  bounties/other/subrion/vulnerability.json
Labels: disclosure

#1386 Cross-Site Scripting (XSS) in v-charts
  bounties/npm/v-charts/1/README.md
  bounties/npm/v-charts/1/vulnerability.json
Labels: disclosure

#1388 Cross-Site Scripting (XSS) in org.igniterealtime.openfire:xmppserver
  bounties/maven/xmppserver/1/README.md
  bounties/maven/xmppserver/1/vulnerability.json
Labels: disclosure

#1404 Prototype Pollution in obj-def
  bounties/npm/obj-def/1/README.md
  bounties/npm/obj-def/1/vulnerability.json
Labels: disclosure

#1408 Cross-Site Scripting (XSS) in openfire-sip-plugin
  bounties/other/openfire-sip-plugin/1/README.md
  bounties/other/openfire-sip-plugin/1/vulnerability.json
Labels: disclosure

#1439 Prototype Pollution in object-agent
  bounties/npm/object-agent/1/README.md
  bounties/npm/object-agent/1/vulnerability.json
Labels: disclosure

#1445 Arbitary code execution Uber petastorm
  bounties/pip/petastorm/1/README.md
  bounties/pip/petastorm/1/vulnerability.json
Labels: disclosure

#1385 Cross-Site Scripting (XSS) in r-chart
  bounties/npm/r-chart/1/README.md
  bounties/npm/r-chart/1/vulnerability.json
Labels: disclosure

#1431 Arbitrary Code Execution in BentoML
  bounties/pip/BentoML/1/README.md
  bounties/pip/BentoML/1/vulnerability.json
Labels: disclosure

#1433 Stored & reflected XSS in - KkFileview
  bounties/other/kkfileview/1/README.md
  bounties/other/kkfileview/1/vulnerability.json
Labels: disclosure

#1435 Prototype Pollution in @szydlovski/deep-object
  bounties/npm/@szydlovski/deep-object/1/README.md
  bounties/npm/@szydlovski/deep-object/1/vulnerability.json
Labels: disclosure

#1436 Prototype Pollution in @blakek/deep
  bounties/npm/@blakek/deep/1/README.md
  bounties/npm/@blakek/deep/1/vulnerability.json
Labels: disclosure

#1437 Prototype Pollution in object-dot
  bounties/npm/object-dot/1/README.md
  bounties/npm/object-dot/1/vulnerability.json
Labels: disclosure

#1440 Stored XSS in Maxsite-CMS
  bounties/other/maxsite/1/README.md
  bounties/other/maxsite/1/vulnerability.json
Labels: disclosure

#1441 Arbitary code execution catalyst
  bounties/pip/catalyst/1/README.md
  bounties/pip/catalyst/1/vulnerability.json
Labels: disclosure

#1544 Adding missing bounties
  bounties/npm/node-im-metadata/1/README.md
  bounties/npm/node-im-metadata/1/vulnerability.json
  bounties/npm/npm-git-publish/1/vulnerability.json
  bounties/packagist/dolibarr/dolibarr/6/README.md
  bounties/packagist/dolibarr/dolibarr/6/vulnerability.json
Labels: bounty upload

#1446 Arbitary Code Execution Apache Spark
  bounties/pip/spark/1/README.md
  bounties/pip/spark/1/vulnerability.json
Labels: disclosure

#1448 Arbitary code execution GCP psq
  bounties/pip/psq/1/README.md
  bounties/pip/psq/1/vulnerability.json
Labels: disclosure

#1450 Arbitrary Code Execution in Google/Caliban
  bounties/pip/caliban/1/README.md
  bounties/pip/caliban/1/vulnerability.json
Labels: disclosure

#1456 Prototype pollution in unbox
  bounties/npm/unbox/1/README.md
  bounties/npm/unbox/1/vulnerability.json
Labels: disclosure

#1457 merge-change vulnerable to Prototype Pollution
  bounties/npm/merge-change/1/README.md
  bounties/npm/merge-change/1/vulnerability.json
Labels: disclosure

#1548 Prototype Pollution in shvl
  bounties/npm/shvl/1/README.md
  bounties/npm/shvl/1/vulnerability.json
Labels: disclosure

#1454 Prototype pollution in @lyngs/merge
  bounties/npm/@lyngs/merge/1/README.md
  bounties/npm/@lyngs/merge/1/vulnerability.json
Labels: disclosure

#1447 Arbitary code execution RedDiscordBot
  bounties/pip/Red-DiscordBot/1/README.md
  bounties/pip/Red-DiscordBot/1/vulnerability.json
Labels: disclosure

#1459 @lyngs/digger vulnerable to Prototype Pollution
  bounties/npm/@lyngs/digger/1/README.md
  bounties/npm/@lyngs/digger/1/vulnerability.json
Labels: disclosure

#1460 Prototype Pollution in xe-utils
  bounties/npm/xe-utils/1/README.md
  bounties/npm/xe-utils/1/vulnerability.json
Labels: disclosure

#1461 Prototype Pollution in deeps
  bounties/npm/deeps/1/README.md
  bounties/npm/deeps/1/vulnerability.json
Labels: disclosure

#1465 Prototype Pollution in @marcopeg/dotted
  bounties/npm/@marcopeg/dotted/1/README.md
  bounties/npm/@marcopeg/dotted/1/vulnerability.json
Labels: disclosure

#1467 Arbitary code execution archivy
  bounties/pip/archivy/1/README.md
  bounties/pip/archivy/1/vulnerability.json
Labels: disclosure

#1466 Arbitary code execution deepmind
  bounties/pip/acme/1/README.md
  bounties/pip/acme/1/vulnerability.json
Labels: disclosure

#1468 Arbitary code execution facebookresearch/parlai
  bounties/pip/ParlAI/1/README.md
  bounties/pip/ParlAI/1/vulnerability.json
Labels: disclosure

#1473 Arbitrary Code Execution in openstack/tripleo-heat-templates/tools
  bounties/other/tripleo-heat-templates/1/README.md
  bounties/other/tripleo-heat-templates/1/vulnerability.json
Labels: disclosure

#1476 Arbitrary Code Execution in pyAudioAnalysis
  bounties/other/pyAudioAnalysis/1/README.md
  bounties/other/pyAudioAnalysis/1/vulnerability.json
Labels: disclosure

#1487 Arbitrary Code Execution in spotify/Postgresql-metrics
  bounties/other/postgresql-metrics/1/README.md
  bounties/other/postgresql-metrics/1/vulnerability.json
Labels: disclosure

#1488 Arbitrary Code Execution in paddlepaddle
  bounties/pip/paddlepaddle/1/README.md
  bounties/pip/paddlepaddle/1/vulnerability.json
Labels: disclosure

#1491 Arbitary code execution @openai/gym
  bounties/pip/gym/1/README.md
  bounties/pip/gym/1/vulnerability.json
Labels: disclosure

#1492 Arbitary code execution @baidu/CUP
  bounties/pip/CUP/1/README.md
  bounties/pip/CUP/1/vulnerability.json
Labels: disclosure

#1493 Arbitary code execution aiocache
  bounties/pip/aiocache/1/README.md
  bounties/pip/aiocache/1/vulnerability.json
Labels: disclosure

#1552 Addition of im-resize bounty
  bounties/npm/im-resize/1/README.md
  bounties/npm/im-resize/1/vulnerability.json
Labels: bounty upload

#1494 Arbitary code execution arq
  bounties/pip/arq/1/README.md
  bounties/pip/arq/1/vulnerability.json
Labels: disclosure

#1495 Prototype Pollution in dset
  bounties/npm/dset/1/README.md
  bounties/npm/dset/1/vulnerability.json
Labels: disclosure

#1496 Prototype Pollution in libnested
  bounties/npm/libnested/1/README.md
  bounties/npm/libnested/1/vulnerability.json
Labels: disclosure

#1497 Prototype Pollution in set-object-value
  bounties/npm/set-object-value/1/README.md
  bounties/npm/set-object-value/1/vulnerability.json
Labels: disclosure

#1498 Prototype Pollution in cache-base
  bounties/npm/cache-base/1/README.md
  bounties/npm/cache-base/1/vulnerability.json
Labels: disclosure

#1499 Arbitrary Code Execution in awslabs/autogluon
  bounties/pip/autogluon/1/README.md
  bounties/pip/autogluon/1/vulnerability.json
Labels: disclosure

#1501 @feizheng/next-object-operator is vulnerable to Prototype Pollution
  bounties/npm/@feizheng/next-object-operator/1/README.md
  bounties/npm/@feizheng/next-object-operator/1/vulnerability.json
Labels: disclosure

#1504 Arbitrary Code Execution in Keras
  bounties/other/keras/1/README.md
  bounties/other/keras/1/vulnerability.json
Labels: disclosure

#1505 Arbitrary Code Execution in Ray
  bounties/pip/ray/1/README.md
  bounties/pip/ray/1/vulnerability.json
Labels: disclosure

#1506 Prototype Pollution in keypather
  bounties/npm/keypather/1/README.md
  bounties/npm/keypather/1/vulnerability.json
Labels: disclosure

#1507 Prototype Pollution in jsonuri
  bounties/npm/jsonuri/1/README.md
  bounties/npm/jsonuri/1/vulnerability.json
Labels: disclosure

#1508 Prototype Pollution in @intrnl/dotprop
  bounties/npm/@intrnl/dotprop/1/README.md
  bounties/npm/@intrnl/dotprop/1/vulnerability.json
Labels: disclosure

#1510 Prototype Pollution in arr-flatten-unflatten
  bounties/npm/arr-flatten-unflatten/1/README.md
  bounties/npm/arr-flatten-unflatten/1/vulnerability.json
Labels: disclosure

#1511 Prototype Pollution in json-glat
  bounties/npm/json-glat/1/README.md
  bounties/npm/json-glat/1/vulnerability.json
Labels: disclosure

#1519 Prototype Pollution in jsonpointerx
  bounties/npm/jsonpointerx/1/README.md
  bounties/npm/jsonpointerx/1/vulnerability.json
Labels: disclosure

#1520 Prototype Pollution in rfc6902-ordered
  bounties/npm/rfc6902-ordered/1/README.md
  bounties/npm/rfc6902-ordered/1/vulnerability.json
Labels: disclosure

#1521 Prototype Pollution in @aofl/object-utils
  bounties/npm/@aofl/object-utils/1/README.md
  bounties/npm/@aofl/object-utils/1/vulnerability.json
Labels: disclosure

#1522 Prototype Pollution in simple-deep-assign
  bounties/npm/simple-deep-assign/1/README.md
  bounties/npm/simple-deep-assign/1/vulnerability.json
Labels: disclosure

#1524 Prototype Pollution in conflate
  bounties/npm/conflate/1/README.md
  bounties/npm/conflate/1/vulnerability.json
Labels: disclosure

#1530 Stored XSS in -Drive db
  bounties/npm/drive-db/1/README.md
  bounties/npm/drive-db/1/vulnerability.json
Labels: disclosure

#1534 Prototype Pollution in merge-options-es5
  bounties/npm/merge-options-es5/1/README.md
  bounties/npm/merge-options-es5/1/vulnerability.json
Labels: disclosure

#1535 Prototype Pollution in dot-expand
  bounties/npm/dot-expand/1/README.md
  bounties/npm/dot-expand/1/vulnerability.json
Labels: disclosure

#1540 Prototype Pollution in deeply-object-assign
  bounties/npm/deeply-object-assign/1/README.md
  bounties/npm/deeply-object-assign/1/vulnerability.json
Labels: disclosure

#1547 Prototype Pollution in latinize
  bounties/npm/latinize/1/README.md
  bounties/npm/latinize/1/vulnerability.json
Labels: disclosure

#1550 Prototype Pollution in homefront
  bounties/npm/homefront/1/README.md
  bounties/npm/homefront/1/vulnerability.json
Labels: disclosure

#1551 Arbitrary Code Execution in TFlearn
  bounties/pip/tflearn/1/README.md
  bounties/pip/tflearn/1/vulnerability.json
Labels: disclosure

#1557 Prototype Pollution in @util-funcs/object-set
  bounties/npm/@util-funcs/object-set/1/README.md
  bounties/npm/@util-funcs/object-set/1/vulnerability.json
Labels: disclosure

#1558 Prototype Pollution in object-accessor
  bounties/npm/object-accessor/1/README.md
  bounties/npm/object-accessor/1/vulnerability.json
Labels: disclosure

#1560 Prototype Pollution in @indlekofer/object_set
  bounties/npm/@indlekofer/object_set/1/README.md
  bounties/npm/@indlekofer/object_set/1/vulnerability.json
Labels: disclosure

#1561 Prototype Pollution in @websanova/vue-dot
  bounties/npm/@websanova/vue-dot/1/README.md
  bounties/npm/@websanova/vue-dot/1/vulnerability.json
Labels: disclosure

#1562 Prototype Pollution in deep-merge-js
  bounties/npm/deep-merge-js/1/README.md
  bounties/npm/deep-merge-js/1/vulnerability.json
Labels: disclosure

#1563 Prototype Pollution in object-deep-key
  bounties/npm/object-deep-key/1/README.md
  bounties/npm/object-deep-key/1/vulnerability.json
Labels: disclosure

#1565 Arbitary code execution distributed
  bounties/pip/distributed/1/README.md
  bounties/pip/distributed/1/vulnerability.json
Labels: disclosure

#1567 Arbitary code execution rqalpha
  bounties/pip/rqalpha/1/README.md
  bounties/pip/rqalpha/1/vulnerability.json
Labels: disclosure

#1568 Arbitary code execution sqlalchemy
  bounties/pip/sqlalchemy/1/README.md
  bounties/pip/sqlalchemy/1/vulnerability.json
Labels: disclosure

#1410 Prototype Pollution in js-data
  bounties/npm/js-data/1/README.md
  bounties/npm/js-data/1/vulnerability.json
Labels: disclosure

#1452 Prototype pollution in Ganon
  bounties/npm/ganon/1/README.md
  bounties/npm/ganon/1/vulnerability.json
Labels: disclosure

#1595 TEST - 7
  bounties/rubygems/jamie-test/1/README.md
  bounties/rubygems/jamie-test/1/vulnerability.json
Labels: disclosure

#1607 Merge local disclosure-accepted workflow to 418sec
  .github/workflows/disclosure-accepted.yml
  package-lock.json
  tools/disclosure-accepted/create-branch.js
  tools/disclosure-accepted/create-fork.js
  tools/disclosure-accepted/get-repository-info.js
Labels: disclosure accepted, enhancement

#1608 Example bounty added
  .github/workflows/disclosure-accepted.yml
  bounties/npm/@ant-design/charts/2/README.md
  bounties/npm/@ant-design/charts/2/vulnerability.json
  tools/disclosure-accepted/get-repository-info.js
Labels: disclosure

#1609 Test bounty
  bounties/npm/@ant-design/charts/3/README.md
  bounties/npm/@ant-design/charts/3/vulnerability.json
Labels: disclosure

#1610 Example bounty
  bounties/npm/@ant-design/charts/2/README.md
  bounties/npm/@ant-design/charts/2/vulnerability.json
Labels: test

#1621 Test: trigger disclosure-submitted workflow
  bounties/npm/angular-redactor/2/README.md
  bounties/npm/angular-redactor/2/vulnerability.json
Labels: disclosure

#1623 Test: trigger workflow
  bounties/maven/argonaut/2/README.md
  bounties/maven/argonaut/2/vulnerability.json
Labels: disclosure

#1624 Test: trigger workflow
  bounties/npm/apikit/2/README.md
  bounties/npm/apikit/2/vulnerability.json
Labels: test

#1625 Test: trigger workflow
  bounties/npm/apikit/2/README.md
  bounties/npm/apikit/2/vulnerability.json
Labels: test

#1626 test(bounties): added test bounty
  bounties/npm/apikit/2/README.md
  bounties/npm/apikit/2/vulnerability.json
Labels: test

#1627 test(bounties): added test bounty - 2
  bounties/npm/apikit/3/README.md
  bounties/npm/apikit/3/vulnerability.json
Labels: test

#1629 chore(bounties): removed example bounty - 4
  bounties/npm/apikit/2/README.md
  bounties/npm/apikit/2/vulnerability.json
Labels: test

#1631 test(bounties): added test bounty
  bounties/npm/apikit/3/README.md
  bounties/npm/apikit/3/vulnerability.json
Labels: test

#1634 test(bounties): added test bounty
  bounties/npm/apikit/2/README.md
  bounties/npm/apikit/2/vulnerability.json
Labels: test

#1635 test(bounties): added test bounty
  bounties/npm/apikit/3/README.md
  bounties/npm/apikit/3/vulnerability.json
Labels: test

#1636 test(bounties): added test bounty
  bounties/npm/apikit/2/README.md
  bounties/npm/apikit/2/vulnerability.json
Labels: test

#1637 test(bounties): added test bounty
  bounties/npm/apikit/3/README.md
  bounties/npm/apikit/3/vulnerability.json
Labels: test

#1638 test(bounties): added test bounty
  bounties/npm/apikit/2/README.md
  bounties/npm/apikit/2/vulnerability.json
Labels: test

#1643 test(bounties): added test bounty
  bounties/npm/apikit/3/README.md
  bounties/npm/apikit/3/vulnerability.json
Labels: test

#1645 test(bounties): added test bounty
  bounties/npm/apikit/2/README.md
  bounties/npm/apikit/2/vulnerability.json
Labels: test

#1648 test(bounties): added test bounty
  bounties/npm/apikit/3/README.md
  bounties/npm/apikit/3/vulnerability.json
Labels: disclosure

#1649 test(bounties): added test bounty
  bounties/npm/apikit/2/README.md
  bounties/npm/apikit/2/vulnerability.json
Labels: disclosure

#1650 test(bounties): added test bounty
  bounties/npm/apikit/3/README.md
  bounties/npm/apikit/3/vulnerability.json
Labels: disclosure

#1655 TEST - 10
  bounties/rubygems/jamie-test/1/README.md
  bounties/rubygems/jamie-test/1/vulnerability.json
Labels: disclosure

#1657 TEST - 11
  bounties/npm/polyfig/1/README.md
  bounties/npm/polyfig/1/vulnerability.json
Labels: disclosure

#1663 Test: trigger workflow
  bounties/npm/apikit/2/README.md
  bounties/npm/apikit/2/vulnerability.json
Labels: disclosure

#1672 Test: trigger workflow
  bounties/npm/apikit/3/README.md
  bounties/npm/apikit/3/vulnerability.json
Labels: disclosure

#1674 test(bounties): added test bounty
  bounties/npm/apikit/2/README.md
  bounties/npm/apikit/2/vulnerability.json
Labels: disclosure

#1681 Test: trigger actions
  bounties/npm/apikit/3/vulnerability.json
Labels: disclosure

#1683 Test: trigger actions
  bounties/npm/apikit/3/vulnerability.json
Labels: disclosure

#1605 Review Disclosure Submitted Action
  .github/workflows/disclosure-submitted.yml
  .github/workflows/process-disclosure.yml
  tools/disclosure-submitted/assets/schemas/vulnerability.json
  tools/disclosure-submitted/contains-a-readme.js
  tools/disclosure-submitted/contains-a-valid-directory.js
  tools/disclosure-submitted/contains-a-valid-json.js
  tools/disclosure-submitted/contains-a-valid-repo.js
  tools/disclosure-submitted/contains-only-db-files.js
  tools/disclosure-submitted/contains-only-new-files.js
  tools/disclosure-submitted/contains-only-one-directory.js
  tools/disclosure-submitted/contains-relevant-package-info.js
  tools/disclosure-submitted/generate-diff.js
  tools/disclosure-submitted/get-package-name.js
  tools/disclosure-submitted/package-lock.json
  tools/disclosure-submitted/package.json
  tools/process-disclosure/contains-a-valid-directory.js
  tools/process-disclosure/contains-a-valid-readme-md.js
  tools/process-disclosure/contains-a-valid-vulnerability-json.js
  tools/process-disclosure/contains-only-bounty-files.js
  tools/process-disclosure/contains-only-new-bounty-files.js
  tools/process-disclosure/contains-only-one-bounty.js
  tools/process-disclosure/generate-diff.js
  tools/process-disclosure/package-lock.json
  tools/shared/analytics.js
  tools/shared/package-lock.json
  tools/shared/package.json
Labels: Release, Review, disclosure submitted

#1688 Disclosure Accepted Action workflow created
  .github/workflows/disclosure-accepted.yml
  .github/workflows/disclosure-submitted.yml
  bounties/other/boxbilling/1/vulnerability.json
  tools/disclosure-accepted/create-branch.js
  tools/disclosure-accepted/create-fork.js
  tools/disclosure-accepted/get-vulnerability-json.js
  tools/disclosure-accepted/package-lock.json
  tools/disclosure-accepted/package.json
  tools/disclosure-accepted/update-vulnerability-json.js
Labels: disclosure accepted

#1706 TEST - 1
  bounties/npm/polyfig/1/README.md
  bounties/npm/polyfig/1/vulnerability.json
Labels: disclosure

#1708 re-trigger
  bounties/npm/apikit/3/README.md
  bounties/npm/apikit/3/vulnerability.json
Labels: disclosure

#1709 TEST - 2
  bounties/npm/polyfig/1/README.md
  bounties/npm/polyfig/1/vulnerability.json
Labels: disclosure

#1711 TEST - 3
  bounties/npm/polyfig/1/README.md
  bounties/npm/polyfig/1/vulnerability.json
Labels: disclosure

#1712 TEST - ADAM
  bounties/npm/polyfig/1/README.md
  bounties/npm/polyfig/1/vulnerability.json
Labels: disclosure

#1714 ADAM - TEST
  bounties/npm/polyfig/1/README.md
  bounties/npm/polyfig/1/vulnerability.json
Labels: disclosure

#1715 BEN - TEST
  bounties/npm/polyfig/1/README.md
  bounties/npm/polyfig/1/vulnerability.json
Labels: disclosure

#1716 FINAL
  bounties/npm/polyfig/1/README.md
  bounties/npm/polyfig/1/vulnerability.json
Labels: disclosure

#1416 Prototype Pollution in objtools
  bounties/npm/objtools/1/README.md
  bounties/npm/objtools/1/vulnerability.json
Labels: disclosure

#1417 Prototype Pollution in @brikcss/merge
  bounties/npm/@brikcss/merge/1/README.md
  bounties/npm/@brikcss/merge/1/vulnerability.json
Labels: disclosure

#1419 Prototype Pollution in @liqd-js/alg-object-merge
  bounties/npm/@liqd-js/alg-object-merge/1/README.md
  bounties/npm/@liqd-js/alg-object-merge/1/vulnerability.json
Labels: disclosure

#1726 chore(bounties): added example bounty
  bounties/npm/apostrophe/2/README.md
  bounties/npm/apostrophe/2/vulnerability.json
Labels: disclosure

#1737 TEST
  bounties/npm/polyfig/1/README.md
  bounties/npm/polyfig/1/vulnerability.json
Labels: automerge, disclosure

#1742 fix: update vulnerability.json contents branch reference
  tools/disclosure-accepted/update-vulnerability-json.js
Labels: bug

#1770 chore(bounties): added testRepository bounty no.3
  bounties/npm/testRepository/3/README.md
  bounties/npm/testRepository/3/vulnerability.json
Labels: disclosure

#1772 chore(bounties): added test bounties in 'other'
  bounties/other/apollo/2/README.md
  bounties/other/apollo/2/vulnerability.json
Labels: automerge, disclosure

#1741 feat(workflows): production preperation
  .github/workflows/disclosure-accepted.yml
  .github/workflows/disclosure-submitted.yml
  tools/disclosure-accepted/get-vulnerability-json.js
  tools/disclosure-accepted/update-vulnerability-json.js
Labels: High

#1773 chore(bounties): removed example bounties
  bounties/npm/testRepository/1/README.md
  bounties/npm/testRepository/1/vulnerability.json
  bounties/npm/testRepository/2/README.md
  bounties/npm/testRepository/2/vulnerability.json
  bounties/npm/testRepository/3/README.md
  bounties/npm/testRepository/3/vulnerability.json
  bounties/other/apollo/2/README.md
  bounties/other/apollo/2/vulnerability.json
Labels: Low

#1778 Cross-Site Scripting (XSS) in frappe-datatable
  bounties/npm/frappe-datatable/1/README.md
  bounties/npm/frappe-datatable/1/vulnerability.json
Labels: automerge, disclosure

#1777 Cross-Site Scripting (XSS) in frappe-gantt
  bounties/npm/frappe-gantt/1/README.md
  bounties/npm/frappe-gantt/1/vulnerability.json
Labels: automerge, disclosure

#1782 Cross-Site Scripting (XSS) in dhtmlx-gantt
  bounties/npm/dhtmlx-gantt/1/README.md
  bounties/npm/dhtmlx-gantt/1/vulnerability.json
Labels: automerge, disclosure

#1784 fix(disclosure-accepted): updated env variable name key for heap
  .github/workflows/disclosure-accepted.yml
Labels: bug

#1785 Prototype Pollution in @thi.ng/paths
  bounties/npm/@thi.ng/paths/1/README.md
  bounties/npm/@thi.ng/paths/1/vulnerability.json
Labels: automerge, disclosure

#1786 Prototype Pollution in tree-kit
  bounties/npm/tree-kit/1/README.md
  bounties/npm/tree-kit/1/vulnerability.json
Labels: automerge, disclosure

#1787 feat(disclosure-submitted): included support ticket url on warning output
  tools/disclosure-submitted/contains-relevant-package-info.js
Labels: enhancement

#1783 Arbitrary Code Execution in TensorFlow
  bounties/pip/tensorflow/1/README.md
  bounties/pip/tensorflow/1/vulnerability.json
Labels: automerge, disclosure

#1789 Prototype Pollution in baobab
  bounties/npm/baobab/1/README.md
  bounties/npm/baobab/1/vulnerability.json
Labels: automerge, disclosure

#1698 Prototype Pollution in object-breacher
  bounties/npm/object-breacher/1/README.md
  bounties/npm/object-breacher/1/vulnerability.json
Labels: automerge, disclosure

#1790 Cross-Site Scripting (XSS) in ibm-gantt-chart
  bounties/npm/ibm-gantt-chart/1/README.md
  bounties/npm/ibm-gantt-chart/1/vulnerability.json
Labels: automerge, disclosure

#1791 Arbitrary Code Execution due to use of eval() in tensorlayer
  bounties/pip/tensorlayer/1/README.md
  bounties/pip/tensorlayer/1/vulnerability.json
Labels: automerge, disclosure

#1792 Prototype Pollution in grpc-node/native-core
  bounties/npm/grpc/2/README.md
  bounties/npm/grpc/2/vulnerability.json
Labels: automerge, disclosure

#1718 Prototype Pollution in dot-prop-opt
  bounties/npm/dot-prop-opt/1/README.md
  bounties/npm/dot-prop-opt/1/vulnerability.json
Labels: automerge, disclosure

#1794 Prototype Pollution in js-data-02
  bounties/npm/js-data/2/README.md
  bounties/npm/js-data/2/vulnerability.json
Labels: automerge, disclosure

#1692 Prototype Pollution in @jswork/next-deep-assign
  bounties/npm/@jswork/next-deep-assign/1/README.md
  bounties/npm/@jswork/next-deep-assign/1/vulnerability.json
Labels: automerge, disclosure

#1776 Cross-Site Scripting (XSS) in frappe-charts
  bounties/npm/frappe-charts/2/README.md
  bounties/npm/frappe-charts/2/vulnerability.json
Labels: disclosure

#1795 Command Injection curljs
  bounties/npm/curljs/1/README.md
  bounties/npm/curljs/1/vulnerability.json
Labels: automerge, disclosure

#1797 Command Injection node-latex-pdf
  bounties/npm/node-latex-pdf/1/README.md
  bounties/npm/node-latex-pdf/1/vulnerability.json
Labels: automerge, disclosure

#1693 Prototype Pollution in objwun
  bounties/npm/objwun/1/README.md
  bounties/npm/objwun/1/vulnerability.json
Labels: automerge, disclosure

#1796 Command Injection s3-kilatstorage
  bounties/npm/s3-kilatstorage/1/README.md
  bounties/npm/s3-kilatstorage/1/vulnerability.json
Labels: automerge, disclosure

#1800 Prototype Pollution in @dotvirus/ptree
  bounties/npm/@dotvirus/ptree/1/README.md
  bounties/npm/@dotvirus/ptree/1/vulnerability.json
Labels: automerge, disclosure

#1801 Prototype Pollution in plain-object-merge
  bounties/npm/plain-object-merge/1/README.md
  bounties/npm/plain-object-merge/1/vulnerability.json
Labels: automerge, disclosure

#1691 Prototype Pollution in nested-object-assign
  bounties/npm/nested-object-assign/1/README.md
  bounties/npm/nested-object-assign/1/vulnerability.json
Labels: automerge, disclosure
