Repository 418sec/huntr, pull requests merged in 2021-02, with the labels that each got.

#1819 Prototype Pollution in obj-keypath
  bounties/npm/obj-keypath/1/README.md
  bounties/npm/obj-keypath/1/vulnerability.json
Labels: automerge, disclosure

#1825 set-each is vulnerable to Prototype Pollution
  bounties/npm/set-each/1/README.md
  bounties/npm/set-each/1/vulnerability.json
Labels: automerge, disclosure

#1824 getsetdeep is vulnerable to Prototype Pollution
  bounties/npm/getsetdeep/1/README.md
  bounties/npm/getsetdeep/1/vulnerability.json
Labels: automerge, disclosure

#1826 Prototype Pollution in propperty
  bounties/npm/propperty/1/README.md
  bounties/npm/propperty/1/vulnerability.json
Labels: automerge, disclosure

#1827 Prototype Pollution in propperties
  bounties/npm/propperties/1/README.md
  bounties/npm/propperties/1/vulnerability.json
Labels: automerge, disclosure

#1830 Prototype Pollution in dot-dotty
  bounties/npm/dot-dotty/1/README.md
  bounties/npm/dot-dotty/1/vulnerability.json
Labels: automerge, disclosure

#1831 Prototype Pollution in json-merge-patch-in-place
  bounties/npm/json-merge-patch-in-place/1/README.md
  bounties/npm/json-merge-patch-in-place/1/vulnerability.json
Labels: automerge, disclosure

#1833 Prototype Pollution in data-store
  bounties/npm/data-store/1/README.md
  bounties/npm/data-store/1/vulnerability.json
Labels: automerge, disclosure

#1834 Prototype Pollution in object-auger
  bounties/npm/object-auger/1/README.md
  bounties/npm/object-auger/1/vulnerability.json
Labels: automerge, disclosure

#1835 Prototype Pollution in utilizes.set
  bounties/npm/utilizes.set/1/README.md
  bounties/npm/utilizes.set/1/vulnerability.json
Labels: automerge, disclosure

#1836 Command Injection in kill-process-on-port
  bounties/npm/kill-process-on-port/1/README.md
  bounties/npm/kill-process-on-port/1/vulnerability.json
Labels: automerge, disclosure

#1837 Command Injection in monorepo-build
  bounties/npm/monorepo-build/1/README.md
  bounties/npm/monorepo-build/1/vulnerability.json
Labels: automerge, disclosure

#1838 Command Injection in xopen
  bounties/npm/xopen/1/README.md
  bounties/npm/xopen/1/vulnerability.json
Labels: automerge, disclosure

#1839 Command Injection in sonar-wrapper
  bounties/npm/sonar-wrapper/1/README.md
  bounties/npm/sonar-wrapper/1/vulnerability.json
Labels: automerge, disclosure

#1840 Command Injection in gitblame
  bounties/npm/gitblame/1/README.md
  bounties/npm/gitblame/1/vulnerability.json
Labels: automerge, disclosure

#1841 Command Injection in ntesseract
  bounties/npm/ntesseract/1/README.md
  bounties/npm/ntesseract/1/vulnerability.json
Labels: automerge, disclosure

#1842 Command Injection in ffmpeg-sdk
  bounties/npm/ffmpeg-sdk/1/README.md
  bounties/npm/ffmpeg-sdk/1/vulnerability.json
Labels: automerge, disclosure

#1843 Command Injection in npos-tesseract
  bounties/npm/npos-tesseract/1/README.md
  bounties/npm/npos-tesseract/1/vulnerability.json
Labels: automerge, disclosure

#1844 Command Injection in total.js
  bounties/npm/total.js/1/README.md
  bounties/npm/total.js/1/vulnerability.json
Labels: automerge, disclosure

#1845 Prototype Pollution in iniparserjs
  bounties/npm/iniparserjs/1/README.md
  bounties/npm/iniparserjs/1/vulnerability.json
Labels: automerge, disclosure

#1846 Command Injection in deferred-exec
  bounties/npm/deferred-exec/1/README.md
  bounties/npm/deferred-exec/1/vulnerability.json
Labels: automerge, disclosure

#1848 Prototype Pollution in decal
  bounties/npm/decal/1/README.md
  bounties/npm/decal/1/vulnerability.json
Labels: automerge, disclosure

#1849 Command Injection on docgenerator
  bounties/npm/docgenerator/1/README.md
  bounties/npm/docgenerator/1/vulnerability.json
Labels: automerge, disclosure

#1526 Reflected XSS in -Teedy
  bounties/other/docs/1/README.md
  bounties/other/docs/1/vulnerability.json
Labels: automerge, disclosure

#1480 SSRF in -Svgedit
  bounties/other/svgedit/1/README.md
  bounties/other/svgedit/1/vulnerability.json
Labels: automerge, disclosure

#1484 stored XSS in - Lucky sheet
  bounties/npm/luckysheet/1/README.md
  bounties/npm/luckysheet/1/vulnerability.json
Labels: automerge, disclosure

#1490 Stored XSS in -Papermerge
  bounties/pip/papermerge/1/README.md
  bounties/pip/papermerge/1/vulnerability.json
Labels: automerge, disclosure

#1527 Stored XSS in -List.js
  bounties/npm/list.js/1/README.md
  bounties/npm/list.js/1/vulnerability.json
Labels: automerge, disclosure

#1486 Stored XSS in -Mobile doc kit
  bounties/npm/mobiledoc-kit/1/README.md
  bounties/npm/mobiledoc-kit/1/vulnerability.json
Labels: automerge, disclosure

#1850 Prototype Pollution in @jswork/next
  bounties/npm/@jswork/next/1/README.md
  bounties/npm/@jswork/next/1/vulnerability.json
Labels: automerge, disclosure

#1851 `Cross Site Scripting` in `dy-server2`
  bounties/npm/dy-server2/1/README.md
  bounties/npm/dy-server2/1/vulnerability.json
Labels: automerge, disclosure

#1853 Prototype Pollution in @fav/prop.set-deep
  bounties/npm/@fav/prop.set-deep/1/README.md
  bounties/npm/@fav/prop.set-deep/1/vulnerability.json
Labels: automerge, disclosure

#1854 Add FreeDiskSpace
  bounties/npm/freediskspace/1/README.md
  bounties/npm/freediskspace/1/vulnerability.json
Labels: automerge, disclosure

#1760 zip-slip in Rc-zip
  bounties/other/rc-zip/1/README.md
  bounties/other/rc-zip/1/vulnerability.json
Labels: automerge, disclosure

#1528 XXE in -Vectalign
  bounties/other/vectalign/1/README.md
  bounties/other/vectalign/1/vulnerability.json
Labels: automerge, disclosure

#1855 Arbitary code execution alphapy
  bounties/pip/alphapy/1/README.md
  bounties/pip/alphapy/1/vulnerability.json
Labels: automerge, disclosure

#1856 Arbitrary Code execution in bonnet
  bounties/other/bonnet/1/README.md
  bounties/other/bonnet/1/vulnerability.json
Labels: automerge, disclosure

#1857 Arbitary code execution studioml
  bounties/pip/studioml/1/README.md
  bounties/pip/studioml/1/vulnerability.json
Labels: automerge, disclosure

#1859 Arbitary code execution simiki
  bounties/pip/simiki/1/README.md
  bounties/pip/simiki/1/vulnerability.json
Labels: automerge, disclosure

#1858 Arbitary code execution labml
  bounties/pip/labml/1/README.md
  bounties/pip/labml/1/vulnerability.json
Labels: automerge, disclosure

#1860 Arbitary Code Execution - dnsrobocert
  bounties/pip/dnsrobocert/1/README.md
  bounties/pip/dnsrobocert/1/vulnerability.json
Labels: automerge, disclosure

#1832 Prototype Pollution in @borderlesslabs/assign
  bounties/npm/@borderlesslabs/assign/1/README.md
  bounties/npm/@borderlesslabs/assign/1/vulnerability.json
Labels: automerge, disclosure

#1861 fix(urls): imported and corrected url formats
  bounties/npm/@auto-it/brew/1/vulnerability.json
  bounties/npm/bson-objectid/1/vulnerability.json
  bounties/npm/cezerin/1/vulnerability.json
  bounties/npm/curlrequest/1/vulnerability.json
  bounties/npm/express-brute/1/vulnerability.json
  bounties/npm/http-server/1/vulnerability.json
  bounties/npm/idevicekit/1/vulnerability.json
  bounties/npm/jison/1/vulnerability.json
  bounties/npm/jshint/1/vulnerability.json
  bounties/npm/macaca-adb/1/vulnerability.json
  bounties/npm/node-imagickal/1/vulnerability.json
  bounties/npm/node-pngdefry/1/vulnerability.json
  bounties/npm/node-pngdefry/2/vulnerability.json
  bounties/npm/node-rpm-builder/1/vulnerability.json
  bounties/npm/node-rsync/1/vulnerability.json
  bounties/npm/node-scp/1/vulnerability.json
  bounties/npm/objutil/1/vulnerability.json
  bounties/npm/safer-eval/1/vulnerability.json
  bounties/npm/simple-open-url/1/vulnerability.json
  bounties/npm/summernote/1/vulnerability.json
  bounties/packagist/lavalite/cms/2/vulnerability.json
Labels: bug

#1700 Prototype Pollution in join-assign
  bounties/npm/join-assign/1/README.md
  bounties/npm/join-assign/1/vulnerability.json
Labels: automerge, disclosure

#1775 Cross-Site Scripting (XSS) in @syncfusion/ej2-base
  bounties/npm/@syncfusion/ej2-base/1/README.md
  bounties/npm/@syncfusion/ej2-base/1/vulnerability.json
Labels: automerge, disclosure

#1768 Arbitrary Code Injection in ejs
  bounties/npm/ejs/1/README.md
  bounties/npm/ejs/1/vulnerability.json
Labels: automerge, disclosure

#1757 Remote Code Execution (RCE) in arpping
  bounties/npm/arpping/1/README.md
  bounties/npm/arpping/1/vulnerability.json
Labels: automerge, disclosure

#1746 Prototype Pollution in obj-helpers
  bounties/npm/obj-helpers/1/README.md
  bounties/npm/obj-helpers/1/vulnerability.json
Labels: automerge, disclosure

#1749 Prototype Pollution in extend-objects-only
  bounties/npm/extend-objects-only/1/README.md
  bounties/npm/extend-objects-only/1/vulnerability.json
Labels: automerge, disclosure

#1862 Prototype Pollution in object-traversed
  bounties/npm/object-traversed/1/README.md
  bounties/npm/object-traversed/1/vulnerability.json
Labels: automerge, disclosure

#1863 Prototype Pollution in object-traverse
  bounties/npm/object-traverse/1/README.md
  bounties/npm/object-traverse/1/vulnerability.json
Labels: automerge, disclosure

#1864 Papermerge
  bounties/pip/papermerge-core/1/README.md
  bounties/pip/papermerge-core/1/vulnerability.json
Labels: automerge, disclosure

#1865 Denial of Service in systeminformation
  bounties/npm/systeminformation/1/README.md
  bounties/npm/systeminformation/1/vulnerability.json
Labels: automerge, disclosure

#1866 Papermerge XSS Via Filename Due To Insecure Errors Reflections
  bounties/pip/papermerge/2/README.md
  bounties/pip/papermerge/2/vulnerability.json
Labels: automerge, disclosure

#1867 feat(append-fork): transferring functionality to 418sec repo for testing
  .github/workflows/disclosure-accepted.yml
  tools/disclosure-accepted/create-fork.js
  tools/disclosure-accepted/update-vulnerability-json.js
  tools/process-bounties/enricher.js
Labels: enhancement, test

#1868 test bounty
  bounties/npm/express-brute/2/README.md
  bounties/npm/express-brute/2/vulnerability.json
Labels: disclosure

#1869 added test bounty
  bounties/npm/express-brute/3/README.md
  bounties/npm/express-brute/3/vulnerability.json
Labels: disclosure

#1872 chore(bounties): added testRepository bounty
  bounties/npm/testRepository/4/README.md
  bounties/npm/testRepository/4/vulnerability.json
Labels: disclosure

#1871 feat(cvss-validation): validating vulnerability.json CVSS field inputs
  .github/workflows/disclosure-submitted.yml
  tools/disclosure-submitted/contains-a-valid-cvss.js
  tools/disclosure-submitted/generate-diff.js
Labels: enhancement

#1875 fix(cvss-validation): breaking on final case, fixed validation
  tools/disclosure-submitted/contains-a-valid-cvss.js
Labels: bug

#1874 Prototype Pollution in @fav/prop.assign-deep
  bounties/npm/@fav/prop.assign-deep/1/README.md
  bounties/npm/@fav/prop.assign-deep/1/vulnerability.json
Labels: automerge, disclosure

#1873 feat(disclosure-accepted): append ForkName to vulnerability.json
  .github/workflows/disclosure-accepted.yml
  tools/disclosure-accepted/create-fork.js
  tools/disclosure-accepted/update-vulnerability-json.js
  tools/process-bounties/enricher.js
Labels: enhancement

#1876 feat(enricher): removed ForkName historical enrichment
  tools/process-bounties/enricher.js
Labels: enhancement

#1559 Prototype Pollution in objer
  bounties/npm/objer/1/README.md
  bounties/npm/objer/1/vulnerability.json
Labels: automerge, disclosure

#1556 Prototype Pollution in obj-resolve
  bounties/npm/obj-resolve/1/README.md
  bounties/npm/obj-resolve/1/vulnerability.json
Labels: automerge, disclosure

#1878 Command Injection in systeminformation
  bounties/npm/systeminformation/2/README.md
  bounties/npm/systeminformation/2/vulnerability.json
Labels: automerge, disclosure

#1877 Instance Takeover On Docs Via Default Cors Misconfig Chained With Broken CSRF Validation.
  bounties/other/docs/2/README.md
  bounties/other/docs/2/vulnerability.json
Labels: automerge, disclosure

#1882 Arbitary code execution in i3wmthemer
  bounties/other/i3wm-themer/1/README.md
  bounties/other/i3wm-themer/1/vulnerability.json
Labels: automerge, disclosure

#1883 Remote Code Execution (RCE) in static-eval
  bounties/npm/static-eval/1/README.md
  bounties/npm/static-eval/1/vulnerability.json
Labels: automerge, disclosure

#1888 Prototype Pollution in propper
  bounties/npm/propper/1/README.md
  bounties/npm/propper/1/vulnerability.json
Labels: automerge, disclosure

#1889 Remote Code Execution (RCE) in curling
  bounties/npm/curling/2/README.md
  bounties/npm/curling/2/vulnerability.json
Labels: automerge, disclosure

#1890 Cross-Site Scripting (XSS) in DaybydayCRM
  bounties/other/DaybydayCRM/1/README.md
  bounties/other/DaybydayCRM/1/vulnerability.json
Labels: automerge, disclosure

#1891 Cross-Site Scripting (XSS) in online-invoicing-system
  bounties/other/online-invoicing-system/1/README.md
  bounties/other/online-invoicing-system/1/vulnerability.json
Labels: automerge, disclosure

#1892 Remote Code Execution (RCE) in imagickal
  bounties/npm/imagickal/1/README.md
  bounties/npm/imagickal/1/vulnerability.json
Labels: automerge, disclosure

#1884 Command Injection in macfromip
  bounties/npm/macfromip/1/README.md
  bounties/npm/macfromip/1/vulnerability.json
Labels: automerge, disclosure

#1885 Command Injection in spritesheet-js
  bounties/npm/spritesheet-js/1/README.md
  bounties/npm/spritesheet-js/1/vulnerability.json
Labels: automerge, disclosure

#1847 Prototype Pollution in ion-parser
  bounties/other/ion-parser/1/README.md
  bounties/other/ion-parser/1/vulnerability.json
Labels: automerge, disclosure

#1886 Command Injection in node-ps
  bounties/npm/node-ps/1/README.md
  bounties/npm/node-ps/1/vulnerability.json
Labels: automerge, disclosure

#1887 Prototype Pollution in js-dot
  bounties/npm/js-dot/1/README.md
  bounties/npm/js-dot/1/vulnerability.json
Labels: automerge, disclosure

#1894 Arbitary code execution label-studio
  bounties/pip/label-studio/1/README.md
  bounties/pip/label-studio/1/vulnerability.json
Labels: automerge, disclosure

#1895 Arbitary code execution pystemon
  bounties/other/pystemon/1/README.md
  bounties/other/pystemon/1/vulnerability.json
Labels: automerge, disclosure

#1896 Arbitary code execution FUNIT
  bounties/other/FUNIT/1/README.md
  bounties/other/FUNIT/1/vulnerability.json
Labels: automerge, disclosure

#1897 DDoS On Shupload Server Due To Lack Of Filenames Validation.
  bounties/other/shupload/1/README.md
  bounties/other/shupload/1/vulnerability.json
Labels: automerge, disclosure

#1899 Prototype Pollution in keyd
  bounties/npm/keyd/1/README.md
  bounties/npm/keyd/1/vulnerability.json
Labels: automerge, disclosure

#1902 Prototype Pollution in o.set
  bounties/npm/o.set/1/README.md
  bounties/npm/o.set/1/vulnerability.json
Labels: automerge, disclosure

#1531 Stored XSS in X-spredsheet
  bounties/npm/x-data-spreadsheet/1/README.md
  bounties/npm/x-data-spreadsheet/1/vulnerability.json
Labels: automerge, disclosure

#1904 XSS in Papermerge-js tag.name
  bounties/other/papermerge-js/1/README.md
  bounties/other/papermerge-js/1/vulnerability.json
Labels: automerge, disclosure

#1898 Local FilesSizes Disclosure On systemInformation Via StatusCode Value.
  bounties/npm/systeminformation/3/README.md
  bounties/npm/systeminformation/3/vulnerability.json
Labels: automerge, disclosure

#1905 Denial Of Service On Shupload Server Due To Lack Of Image Size Validation Can Fill-Up The Server Storage.
  bounties/other/shupload/2/README.md
  bounties/other/shupload/2/vulnerability.json
Labels: automerge, disclosure

#1906 Arbitary code execution himl
  bounties/pip/himl/1/README.md
  bounties/pip/himl/1/vulnerability.json
Labels: automerge, disclosure

#1907 Arbitary code execution ops-cli
  bounties/pip/ops-cli/1/README.md
  bounties/pip/ops-cli/1/vulnerability.json
Labels: automerge, disclosure

#1908 Arbitary code execution - kappa
  bounties/pip/kappa/1/README.md
  bounties/pip/kappa/1/vulnerability.json
Labels: automerge, disclosure

#1909 Arbitary code execution - jrnl
  bounties/pip/jrnl/1/README.md
  bounties/pip/jrnl/1/vulnerability.json
Labels: automerge, disclosure

#1910 Arbitary code execution - End to end asr pytorch
  bounties/other/End-to-end-ASR-Pytorch/1/README.md
  bounties/other/End-to-end-ASR-Pytorch/1/vulnerability.json
Labels: automerge, disclosure

#1911 Cross-Site Scripting (XSS) in tui.editor
  bounties/other/tui.editor/1/README.md
  bounties/other/tui.editor/1/vulnerability.json
Labels: automerge, disclosure

#1912 Cross-Site Scripting (XSS) in @toast-ui/chart
  bounties/npm/@toast-ui/chart/1/README.md
  bounties/npm/@toast-ui/chart/1/vulnerability.json
Labels: automerge, disclosure

#1913 Cross-Site Scripting (XSS) in tui-grid
  bounties/npm/tui-grid/1/README.md
  bounties/npm/tui-grid/1/vulnerability.json
Labels: automerge, disclosure

#1914 Cross-Site Scripting (XSS) in tui-calendar
  bounties/npm/tui-calendar/1/README.md
  bounties/npm/tui-calendar/1/vulnerability.json
Labels: automerge, disclosure

#1917 Command Injection in lodash
  bounties/npm/lodash/1/README.md
  bounties/npm/lodash/1/vulnerability.json
Labels: automerge, disclosure

#1918 Arbitary code execution in voxceleb_trainer
  bounties/other/voxceleb_trainer/1/README.md
  bounties/other/voxceleb_trainer/1/vulnerability.json
Labels: automerge, disclosure

#1919 Arbitary code execution lastinfosec
  bounties/other/lastinfosec/1/README.md
  bounties/other/lastinfosec/1/vulnerability.json
Labels: automerge, disclosure

#1920 Arbitary code execution synchronizer connector
  bounties/other/synchronizer/1/README.md
  bounties/other/synchronizer/1/vulnerability.json
Labels: automerge, disclosure

#1921 Arbitary code execution neurom
  bounties/pip/neurom/1/README.md
  bounties/pip/neurom/1/vulnerability.json
Labels: automerge, disclosure

#1549 SSRF in - Keystonejs
  bounties/npm/keystone/1/README.md
  bounties/npm/keystone/1/vulnerability.json
Labels: automerge, disclosure

#1922 Arbitary code execution in Ymir-test
  bounties/other/Ymir-Test/1/README.md
  bounties/other/Ymir-Test/1/vulnerability.json
Labels: automerge, disclosure

#1923 Arbitary code execution on OnboardingTool
  bounties/other/OnboardingTool/1/README.md
  bounties/other/OnboardingTool/1/vulnerability.json
Labels: automerge, disclosure

#1924 Arbitary code execution on InverseHeartActivity
  bounties/other/RolandGit95-InverseHeartActivity/1/README.md
  bounties/other/RolandGit95-InverseHeartActivity/1/vulnerability.json
Labels: automerge, disclosure

#1925 Arbitary code execution in aviatracker
  bounties/other/aviatracker/1/README.md
  bounties/other/aviatracker/1/vulnerability.json
Labels: automerge, disclosure

#1926 Arbitary code execution on DeepFriedBot
  bounties/other/DeepFriedBot/1/README.md
  bounties/other/DeepFriedBot/1/vulnerability.json
Labels: automerge, disclosure

#1927 Arbitary code execution in nlp-vietnamese-text-summarization
  bounties/other/nlp-vietnamese-text-summarization/1/README.md
  bounties/other/nlp-vietnamese-text-summarization/1/vulnerability.json
Labels: automerge, disclosure

#1928 Arbitrary code execution in bjm_move
  bounties/other/bjm_move/1/README.md
  bounties/other/bjm_move/1/vulnerability.json
Labels: automerge, disclosure

#1546 Reflected XSS in -Book stack
  bounties/other/BookStack/1/README.md
  bounties/other/BookStack/1/vulnerability.json
Labels: automerge, disclosure

#1929 Server-Side Request Forgery in systeminformation
  bounties/npm/systeminformation/4/README.md
  bounties/npm/systeminformation/4/vulnerability.json
Labels: automerge, disclosure

#1930 Arbitrary code execution in Access-Control
  bounties/other/Access-Control/1/README.md
  bounties/other/Access-Control/1/vulnerability.json
Labels: automerge, disclosure

#1477 Stored XSS in -Joedit
  bounties/npm/jodit/1/README.md
  bounties/npm/jodit/1/vulnerability.json
Labels: automerge, disclosure

#1478 Stored XSS in -Tinyfilemanger
  bounties/other/tinyfilemanager/1/README.md
  bounties/other/tinyfilemanager/1/vulnerability.json
Labels: automerge, disclosure

#1482 SSRF in - Method-Draw
  bounties/other/Method-Draw/1/README.md
  bounties/other/Method-Draw/1/vulnerability.json
Labels: automerge, disclosure

#1483 SSRF in -Svgomg
  bounties/other/svgomg/1/README.md
  bounties/other/svgomg/1/vulnerability.json
Labels: automerge, disclosure

#1485 stored XSS in -Trumbowyg
  bounties/npm/trumbowyg/1/README.md
  bounties/npm/trumbowyg/1/vulnerability.json
Labels: automerge, disclosure

#1545 zip-slip in Mucommander
  bounties/other/mucommander/1/README.md
  bounties/other/mucommander/1/vulnerability.json
Labels: automerge, disclosure

#1932 Arbitrary code execution in Mixmatch-pytorch
  bounties/other/MixMatch-Pytorch-Implementation/1/README.md
  bounties/other/MixMatch-Pytorch-Implementation/1/vulnerability.json
Labels: automerge, disclosure

#1934 Arbitrary code execution in cameras_robonomics
  bounties/other/cameras_robonomics/1/README.md
  bounties/other/cameras_robonomics/1/vulnerability.json
Labels: automerge, disclosure

#1935 Arbitrary code execution in router-tracker
  bounties/other/router_tracker/1/README.md
  bounties/other/router_tracker/1/vulnerability.json
Labels: automerge, disclosure

#1936 Arbitary Code Execution in hatespeech
  bounties/other/hatespeech/1/README.md
  bounties/other/hatespeech/1/vulnerability.json
Labels: automerge, disclosure

#1937 Arbitary code execution simple playgrounds
  bounties/pip/simple-playgrounds/1/README.md
  bounties/pip/simple-playgrounds/1/vulnerability.json
Labels: automerge, disclosure

#1938 Arbitary code execution reqman
  bounties/pip/reqman/1/README.md
  bounties/pip/reqman/1/vulnerability.json
Labels: automerge, disclosure

#1941 Prototype Pollution in strip-ansi (Re-Pull Request of https://github.com/418sec/huntr/pull/1570 )
  bounties/npm/strip-ansi/1/README.md
  bounties/npm/strip-ansi/1/vulnerability.json
Labels: automerge, disclosure

#1943 Arbitary Code Execution in Jinjafx
  bounties/other/jinjafx/1/README.md
  bounties/other/jinjafx/1/vulnerability.json
Labels: automerge, disclosure

#1944 Arbitrary Code Execution in Arewefastyet
  bounties/other/arewefastyet/1/README.md
  bounties/other/arewefastyet/1/vulnerability.json
Labels: automerge, disclosure

#1939 Arbitrary Code Execution in Cross domain segmentation
  bounties/other/Cross-Domain-Segmentation/1/README.md
  bounties/other/Cross-Domain-Segmentation/1/vulnerability.json
Labels: automerge, disclosure

#1947 tools of GRPC was vulnerable to arbitrary code execution
  bounties/other/grpc/1/README.md
  bounties/other/grpc/1/vulnerability.json
Labels: automerge, disclosure

#1948 Arbitary Code Execution in PyralleX2
  bounties/other/PyralleX2/1/README.md
  bounties/other/PyralleX2/1/vulnerability.json
Labels: automerge, disclosure

#1949 Arbitrary Code Execution in Central api cli
  bounties/other/central-api-cli/1/README.md
  bounties/other/central-api-cli/1/vulnerability.json
Labels: automerge, disclosure

#1946 Arbitary Code execution in Zapta
  bounties/other/Zapata/1/README.md
  bounties/other/Zapata/1/vulnerability.json
Labels: automerge, disclosure

#1942 Arbitrary Code Execution in altair
  bounties/pip/altair/1/README.md
  bounties/pip/altair/1/vulnerability.json
Labels: automerge, disclosure

#1950 Arbitary Code execution in 17g
  bounties/other/17g/1/README.md
  bounties/other/17g/1/vulnerability.json
Labels: automerge, disclosure

#1951 Arbitary code execution in kindle
  bounties/pip/kindle/1/README.md
  bounties/pip/kindle/1/vulnerability.json
Labels: automerge, disclosure

#1952 Arbitary code execution yolov5
  bounties/other/yolov5/2/README.md
  bounties/other/yolov5/2/vulnerability.json
Labels: automerge, disclosure

#1953 Arbitary code exection sodasql
  bounties/pip/soda-sql/1/README.md
  bounties/pip/soda-sql/1/vulnerability.json
Labels: automerge, disclosure

#1954 Arbitary Code Execution in Neovision
  bounties/other/neovision/1/README.md
  bounties/other/neovision/1/vulnerability.json
Labels: automerge, disclosure

#1955 Arbitary Code Execution in Finance tracker
  bounties/other/financeTracker/1/README.md
  bounties/other/financeTracker/1/vulnerability.json
Labels: automerge, disclosure

#1956 Arbitary Code Execution in Asl
  bounties/other/ASL/1/README.md
  bounties/other/ASL/1/vulnerability.json
Labels: automerge, disclosure

#1957 Arbitary Code Execution in -Swagger
  bounties/other/swagger/1/README.md
  bounties/other/swagger/1/vulnerability.json
Labels: automerge, disclosure

#1958 Arbitrary Code Execution in Hyper kube config
  bounties/other/hyper-kube-config/1/README.md
  bounties/other/hyper-kube-config/1/vulnerability.json
Labels: automerge, disclosure

#1959 Arbitrary Code Execution On Simba Due To Insecure YAML Parsing.
  bounties/pip/simba-uw-tf/1/README.md
  bounties/pip/simba-uw-tf/1/vulnerability.json
Labels: automerge, disclosure
